### ISSUE TITLE
Can't figure out how to rotate a box

### ISSUE THREAD

**Issue by flycast** [RiSearcher/GeometRi.CSharp#11]
Love your library and am using it quite a lot. I am having an issue rotating a box. What am I doing wrong? I have tried many things. I basically need the box to orient using the three points. 

```
            g.Point3d centerPoint = new g.Point3d(17.2489, 19.8042, -0.307304);
            g.Point3d rightWing = new g.Point3d(17.7258, 19.7956, -0.303844);
            g.Point3d rearward = new g.Point3d(17.26, 19.8038, -0.289645);
            g.Box3d box = new g.Box3d(centerPoint, 0.05, 0.02, 0.01);
            g.Coord3d coord = new g.Coord3d(centerPoint, rightWing, rearward);
            g.Rotation rot = box.Orientation.ConvertTo(coord);
            box = box.Rotate(rot, box.Center);
```

**Comment by RiSearcher** [comment]
I think the most confusing line is this:
`g.Rotation rot = box.Orientation.ConvertTo(coord);`
Let's analyse what happens there step by step:

1.  box - you have defined your box in global coordinate system, therefore it is axis aligned box and it's orientation equals to zero rotation.

2. box.Orientation - this returns rotation object, which equals to the rotation needed to convert axis aligned box to your box (not including center point translation, of course). But since your box is already axis aligned, this operation will return zero rotation object.

3. box.Orientation.ConvertTo(coord) - this converts rotation object, obtained in previous step, to local coordinate system. However, the way GeometRi works, once you have created rotation, it will represent rotation action in 3D space, not matter what local CS you use. ConvertTo method changes internal representation of the rotation object, namely its rotation matrix stored inside (and you may get out this converted rotation matrix). But together with rotation matrix object stores reference coordinate system, and the final action will be the same. In your case the result of this operation still will be zero rotation.

There are number of ways to accomplish what you need. For example:
`            g.Box3d box2 = new g.Box3d(centerPoint, 0.05, 0.02, 0.01);
            g.Rotation rot2 = new g.Rotation(coord);
            box2 = box2.Rotate(rot2, box2.Center);`
Here you define box in global CS, then create rotation object from global to local CS and then rotate your box. But you can do in one line, directly defining your box in local CS:
`g.Box3d box3 = new g.Box3d(centerPoint, 0.05, 0.02, 0.01, coord);`

**Comment by flycast** [comment]
Perfect! Thank you again.
