### ISSUE TITLE
Segment Intersection not working properly

### ISSUE THREAD

**Issue by davidarh** [RiSearcher/GeometRi.CSharp#15]
Hi,

I am performing 3d segment intersections but am getting inconsistent results in some cases where small precision errors generate tiny differences. Interestingly, intersecting in one direction works, and intersecting in the opposite direction doesn't.

Example:

>  intersectSegment.IntersectionWith(lineSeg3d)
null
> lineSeg3d.IntersectionWith(intersectSegment)
Segment:
Point 1  -> (    399.83,     255.06,          0)
Point 2 -> (    421.64,     255.06,          0)

ADDITIONAL INFO

> intersectSegment.ToString()
"Segment:
Point 1  -> (    399.83,     255.06,          0)
Point 2 -> (    453.16,     255.06,          0)"
> lineSeg3d.ToString()
"Segment:
Point 1  -> (    389.99,     255.06,          0)
Point 2 -> (    421.64,     255.06,          0)"
> intersectSegment.ToLine.DistanceTo(lineSeg3d.ToLine)
0
> intersectSegment.Direction.Normalized
Vector3d -> (         1,  1.279e-14,          0)
> lineSeg3d.Direction.Normalized
Vector3d -> (         1, -3.5925e-15,          0)

**Comment by RiSearcher** [comment]
Hi, I cannot reproduce your results with provided data. The code:
    Segment3d intersectSegment = new Segment3d(new Point3d(399.83, 255.06, 0), new Point3d(453.16, 255.06, 0));
    Segment3d lineSeg3d = new Segment3d(new Point3d(389.99, 255.06, 0), new Point3d(421.64, 255.06, 0));

    object obj1 = intersectSegment.IntersectionWith(lineSeg3d);
    Console.WriteLine(obj1.ToString());

    object obj2 = lineSeg3d.IntersectionWith(intersectSegment);
    Console.WriteLine(obj2.ToString());

    Console.WriteLine(intersectSegment.Direction.Normalized.ToString());
    Console.WriteLine(lineSeg3d.Direction.Normalized.ToString());
produces next output:
    Segment:
    Point 1  -> (    399.83,     255.06,          0)
    Point 2 -> (    421.64,     255.06,          0)
    Segment:
    Point 1  -> (    399.83,     255.06,          0)
    Point 2 -> (    421.64,     255.06,          0)
    Vector3d -> (         1,          0,          0)
    Vector3d -> (         1,          0,          0)

Probably you segments are not exactly parallel, and in this case due to round-off error different results could be obtained. May be you can try different tolerance value: GeometRi3D.Tolerance. Default value is 1e-12.

**Comment by davidarh** [comment]
Thank you,

I tried changing the tolerance and this effectively solves the problem. However, it is odd that the intersection results are different if done form the perspective of one segment or the other.

Maybe the algorithm can be modified to always test in both directions? Even though it is a tolerance issue it is desirable to have the same result when testing in both directions.

**Comment by RiSearcher** [comment]
Hi, I have rewritten this method and now it should give more consistent results.
However, still in case of two overlapping almost parallel segments it will return overlapping part of one segment when applied in one direction, and overlapping part of other segment when applied in other direction. But since the distance between such segments is less then tolerance, the library will treat them as equal segments in other operations.

**Comment by davidarh** [comment]
Great! thank you
