### ISSUE TITLE
How to get angles of global axis rotation

### ISSUE THREAD

**Issue by vinczet** [RiSearcher/GeometRi.CSharp#20]
Hi Sergey,
Please help me with the following issue.
We have a global coordinate system X,Y,Z
There are 3 origin vectors (perpendicular to each orher (Cartesian) with unit length): V1, V2, V3.
There are 3 target vectors (perpendicular to each orher (Cartesian) with unit length): U1, U2, U3.
I have to get the 3 angles which are rotation angles around the global axes ta get from V1, V2, V3 to U1, U2, U3.
I am happy to see that your library contains quaternions.
Although I am not familiar with quaternions, but probably it would be the easyest if I created 2 orientation quaternions q1 = V1,V2,V3; q2 = U1,U2,U3
There is an equation: q2 =  q1 * S
q2 * inverse(q1) = S
S is the rotation transformation which transforms V1,V2,V3 to U1,U2,U3.
How can I get from S the rotation angles on X, Y, Z?
![Coordinate_rotation](https://user-images.githubusercontent.com/50625436/125164678-bc44ce00-e193-11eb-9ff9-8965b1bc1aa4.png)
Thanky ou for your help!
Tamás

**Comment by RiSearcher** [comment]
Hi!
I don't know a short way to do what you want, but one possible solution is next.

1. Create rotation objects to rotate from global CS to local CS V123 and G123. To do so you need to create local CS first.
2. Create quaternions from these two rotations: q1 and q2.
3. Get quaternion transformation from q1 to q2 and convert it back to rotation object.
4. Convert rotation object to Euler angles.

`// Create local coordinate systems`
`Coord3d c1 = new Coord3d(new Point3d(), v1, v2);`
`Coord3d c2 = new Coord3d(new Point3d(), g1, g2);`
`// Create rotations from global CS to local CS`
`Rotation r1 = new Rotation(c1);`
`Rotation r2 = new Rotation(c2);`
`// Create quaternions from rotations`
`Quaternion q1 = new Quaternion(r1.ToRotationMatrix);`
`Quaternion q2 = new Quaternion(r2.ToRotationMatrix);`
`// Get transformation from q1 to q2`
`Quaternion q12 = q2 * q1.Inverse();`
`// Convert quaternion to rotation and get Euler angles`
`Rotation r12 = new Rotation(q12);`
`double[] angles = r12.ToEulerAngles("xyz");`

You can use other order of axes instead of "xyz", and use capital letters if you need angles in moving frame ("XYZ")
