### ISSUE TITLE
Question: difference from MathNet.Spatial (?)

### ISSUE THREAD

**Issue by jkalias** [RiSearcher/GeometRi.CSharp#28]
Hi,

I noticed you were involved in the past in the development of [MathNet.Spatial](https://github.com/mathnet/mathnet-spatial) . May I ask what the difference of this library is compared to Spatial, or why you decided to write your own?

**Comment by RiSearcher** [comment]
Hi!
I never really participated in MathNet.Spatial development. I considered this option at the beginning, when I ported initial version of the GeometRi from VB.Net to C#. But I didn't like some of the naming conventions and very slow development speed of MathNet.Spatial. Since I use GeometRi in several own projects, it was more convenient to implement types and methods that I need at the moment into own library.

**Comment by jkalias** [comment]
Thanks for your prompt reply!

> But I didn't like some of the naming conventions and very slow development speed of MathNet.Spatial.

I fully understand what you say... especially the development speed and/or the care shown in the project. It could become quite powerful and useful. I tried to push the release of a stable 1.0 version, but I faced considerable backlash from the other members (I was recently accepted as a co-maintainer of Spatial)
